# Generated by Django 5.2.4 on 2025-07-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passageiro', '0002_passageiro_cod_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='status',
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
