# Generated by Django 5.2 on 2025-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poltrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cod_passageiro', models.IntegerField()),
                ('cod_viagem', models.IntegerField()),
                ('cod_pagamento', models.IntegerField()),
                ('status', models.IntegerField(db_default=1, default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
