# Generated by Django 5.2 on 2025-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poltrona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poltrona',
            name='cod_pagamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poltrona',
            name='cod_passageiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poltrona',
            name='cod_viagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poltrona',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
