# Generated by Django 5.2 on 2025-06-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poltrona', '0002_alter_poltrona_cod_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poltrona',
            name='cod_pagamento',
        ),
        migrations.RemoveField(
            model_name='poltrona',
            name='cod_passageiro',
        ),
        migrations.AddField(
            model_name='poltrona',
            name='cod_usuario',
            field=models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
