# Generated by Django 5.2 on 2025-04-15 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora_partida', models.TimeField()),
                ('hora_chegada', models.TimeField()),
                ('local_partida', models.CharField(db_default='', max_length=200)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(db_default='')),
                ('obs', models.TextField(db_default='')),
                ('acentos_andar1d', models.IntegerField(db_default=1)),
                ('acentos_andar1e', models.IntegerField(db_default=1)),
                ('acentos_andar2d', models.IntegerField(db_default=1)),
                ('acentos_andar2e', models.IntegerField(db_default=1)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('cod_usuario', models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
