# Generated by Django 5.2 on 2025-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0003_alter_viagem_descricao_alter_viagem_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='acentos_andar2d',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='acentos_andar2e',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
