# Generated by Django 5.2 on 2025-06-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poltrona', '0003_remove_poltrona_cod_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_default=1, default=1)),
                ('forma_pagamento', models.CharField(default='Pendente', max_length=50)),
                ('id_pagamento', models.CharField(default='Pendente', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cod_poltrona', models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to='poltrona.poltrona')),
            ],
        ),
    ]
