# Generated by Django 5.2 on 2025-06-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='grupo',
            field=models.IntegerField(default=0),
        ),
    ]
