# Generated by Django 5.2 on 2025-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='grupo',
            field=models.CharField(default='0', editable=False, max_length=12, unique=True),
        ),
    ]
