# Generated by Django 5.2 on 2025-06-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='grupo',
            field=models.CharField(editable=False, max_length=12),
        ),
    ]
